/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IPlatformToken } from "./IPlatformToken";
export type { PlatformTreasury } from "./PlatformTreasury";
