/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as platformTreasurySol from "./PlatformTreasury.sol";
export type { platformTreasurySol };
export type { MockUSDT } from "./MockUSDT";
export type { PlatformToken } from "./PlatformToken";
