/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as platformTreasurySol from "./PlatformTreasury.sol";
export { MockUSDT__factory } from "./MockUSDT__factory";
export { PlatformToken__factory } from "./PlatformToken__factory";
