/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IPlatformToken__factory } from "./IPlatformToken__factory";
export { PlatformTreasury__factory } from "./PlatformTreasury__factory";
